#! /bin/bash
#
# Johannes Meixner <jsmeix@suse.de>, 2004, 2005

#set -x

export PATH="/sbin:/usr/sbin:/usr/bin:/bin"
export LC_ALL="POSIX"
export LANG="POSIX"
umask 022

MY_NAME=${0##*/}
OUTPUT_FORMAT="$1"
[ -z "$OUTPUT_FORMAT" ] && OUTPUT_FORMAT="ASCII"
[ "$OUTPUT_FORMAT" != "ASCII" -a "$OUTPUT_FORMAT" != "YCP" ] && { echo -en "\nUsage:\n$MY_NAME {ASCII|YCP}\n" 1>&2 ; exit 1 ; }

NET_BACKEND_CONFIG_FILE="/etc/sane.d/net.conf"
SANED_CONFIG_FILE="/etc/sane.d/saned.conf"

# Get and output the hosts in $NET_BACKEND_CONFIG_FILE
if [ -r $NET_BACKEND_CONFIG_FILE ]
then [ "$OUTPUT_FORMAT" = "YCP" ] && echo -n "\$[ \"net_backend_hosts\":\"" || echo -n "Hosts in $NET_BACKEND_CONFIG_FILE: "
     grep -v '^#' $NET_BACKEND_CONFIG_FILE | tr -s '\n' ',' | tr -d '[:space:]' | sed -e 's/,$//'
     [ "$OUTPUT_FORMAT" = "YCP" ] && echo "\"," || echo
else 
    echo "Cannot read $NET_BACKEND_CONFIG_FILE" 1>&2
    exit 2
fi

# Get and output the hosts or subnets in $SANED_CONFIG_FILE
if [ -r $SANED_CONFIG_FILE ]
then [ "$OUTPUT_FORMAT" = "YCP" ] && echo -n "   \"saned_hosts\":\"" || echo -n "Hosts or subnets in $SANED_CONFIG_FILE: "
     grep -v '^#' $SANED_CONFIG_FILE | tr -s '\n' ',' | tr -d '[:space:]' | sed -e 's/,$//'
     [ "$OUTPUT_FORMAT" = "YCP" ] && echo -e "\"\n]" || echo
else 
    echo "Cannot read $SANED_CONFIG_FILE" 1>&2
    exit 3
fi

exit 0

