#! /bin/bash

# Johannes Meixner <jsmeix@suse.de>, 2004, 2005, 2006, 2007, 2008, 2010
#
# Copyright (c) 2010 Novell, Inc.
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact Novell, Inc.
#
# To contact Novell about this file by physical or electronic mail,
# you may find current contact information at www.novell.com

#set -x

export PATH="/sbin:/usr/sbin:/usr/bin:/bin"
export LC_ALL="POSIX"
export LANG="POSIX"
umask 022

# The hpaio driver and the ptal service exclude each other.
# Disable the ptal service if it exists:
if [ -x /etc/init.d/ptal ]
then /etc/init.d/ptal stop
     insserv -r ptal
fi

# Since HPLIP version 2.8.4 there are no longer any startup daemons.
# The hplip init script was adapted to provide backward compatibility:
# It still exists to avoid that printer/scanner setup tools fail
# when they try to enable the "hplip" service but all it does
# is to stop a possibly running hpssd.
# To be on the safe side, disable the hplip service if it exists:
if [ -x /etc/init.d/hplip ]
then /etc/init.d/hplip stop
     insserv -r hplip
fi

# Exit successfully in any case:
exit 0

