#! /bin/bash
#
# Johannes Meixner <jsmeix@suse.de>, 2004, 2005, 2006, 2007, 2008

#set -x

export PATH="/sbin:/usr/sbin:/usr/bin:/bin"
export LC_ALL="POSIX"
export LANG="POSIX"
umask 022

# The hpaio driver and the ptal service exclude each other.
# Disable the ptal service if it exists:
if [ -x /etc/init.d/ptal ]
then /etc/init.d/ptal stop
     insserv -r ptal
fi

# Since HPLIP version 2.8.4 there are no longer any startup daemons.
# The hplip init script was adapted to provide backward compatibility:
# It still exists to avoid that printer/scanner setup tools fail
# when they try to enable the "hplip" service but all it does
# is to stop a possibly running hpssd.
# To be on the safe side, disable the hplip service if it exists:
if [ -x /etc/init.d/hplip ]
then /etc/init.d/hplip stop
     insserv -r hplip
fi

# Exit successfully in any case:
exit 0

