#!/usr/bin/perl
#
# ag_scanner
# This script is part of the YaST2 Scanner installation module
# Copyright SuSE Gmbh - 2001
# 
# Author: Klaas Freitag <freitag@suse.de>
#
# $Id$
#

# ag_scanner provides two different functions, selected through the
# ycp 'path', which is mapped to the perl var $action in this script. 
# 
# The first action, 'scsi', queries the system for know SCSI scanners.
# This is a kind of hardware detection, the devices  need not to be configured
#  in SANE but are also found if they are.
#
# The second action, 'configured', returns all scan devices configured in SANE.
# This is done by calling scanimage -s (a patched version) which returns the
# sane configured scanners, even network accessible scanners.
#

BEGIN { unshift @INC, "/usr/lib/YaST2/agents_non_y2/";
	unshift @INC, "/usr/lib/YaST2/servers_non_y2/"; }

use strict;
use ycp;

use scannerDB;
# ##############################################################################

my @scanners;

while ( <STDIN> )
{
    ycpDoVerboseLog();
    ycpInit( $_ );

    if( /result/i )
    {
	y2debug("got result -> say goodby!" );
	exit(0);
    }

    my $action = ycpGetPath();
    y2debug( " vvv starting in ag_scanner vvv" );

    y2debug( "Got Action = ycpPath = <$action>");

    if( $action =~ /scsi/i )
    {
	y2debug( "Performing scsi bus scan for scanners!" );
	my $cmd = "/usr/X11R6/bin/sane-find-scanner -s";
	@scanners = ();

	if( open( CMD, "$cmd |" ) )
	{
	    my $cnt = 0;
	    while( my $cmd = <CMD> )
	    {
		chomp( $cmd );
		my ($devfile, $class, $vendor, $model) = split( /\s+\"/, $cmd );
		$class   =~ s/\"//g;
		$vendor  =~ s/\"//g;
		$model   =~ s/\"//g;

		y2debug( "Found $class $vendor $model on $devfile" );

		# Check if there are links and skip them
		if( -l $devfile ) 
		{
		    y2debug( "$devfile is a link -> skipping !" );
		    next;
		}
	
		push ( @scanners , 
		{ bus => "SCSI", 
		      class_id => "",
		      device => $model,
		      device_id => "",
		      resource =>"",
		      rev => "",
		      sub_class_id => "",
		      sub_device => $model,
		      sub_vendor => $vendor,
		      unique_key => "",
		      vendor => $vendor,
		      vendor_id => "",
		      dev_name => $devfile } );
		$cnt ++;
	    }
	    close CMD;
	    y2debug( "Found $cnt scsi-scanners !");
	}
	else
	{
	    y2debug( "ERROR: Could not open sane-find-scanner!" );
	}

    }
    elsif( $action =~ /configured/i )
    {
         @scanners = performScanimage();
    }
    else
    {
        y2debug( "ERROR: Unspecified action !" );
    }
    y2debug (" ^^^ Leaving ag_scanner - goodbye ^^^" );

    ycpReturn( \@scanners );

}
