#!/bin/sh
#
# $Id$
#
# Driverlisten
echo 'Read( .driverlist, $[ "bus":"SCSI", "vendor":"UMAX" ])'  | ag_sane > test/driverlist1.txt
echo 'Read( .driverlist, $[ "bus":"SCsi", "vendor":"UMAX" ])'  | ag_sane > test/driverlist2.txt

# Vendorliste
echo 'Read( .vendorlist, $[ "bus":"SCSI" ])' | ag_sane > test/vendorlist.txt

# Eine Umax-definition schreiben
export PREFIX_DIR=`pwd`/test

echo 'Read( .writeconfig, $[ "bus":"SCSI", "vendor":"UMAX","devicefile":"/dev/scanner", "driver":"umax" ])' | ag_sane
# und ändern
echo 'Read( .writeconfig, $[ "bus":"SCSI", "vendor":"UMAX","devicefile":"/dev/sg0", "driver":"umax" ])' | ag_sane

echo 'Read( .netscannerinfo, $[ "bus":"Net", "host":"d142.suse.de" ])' | ag_sane

exit

# Scan an image 
echo 'Read( .scanimage, $[ "bus":"net", "vendor":"UMAX", "devicefile":"/dev/sg0", "host":"d142" ])' | ag_sane > config.txt
# difference=`diff driverlist1.txt driverlist2.txt`

if [ "$difference" == "" ]
then
	echo "OK"
fi



#
#





