
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Package:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/head/containers/yast-cpp:latest
      options: --privileged

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: rake build_dependencies:install

    - name: Package Build
      run: yast-ci-cpp

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/head/containers/yast-ruby:latest
      options: --privileged

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: POT Check
      run: rake check:pot

    - name: POT Check
      run: rake check:syntax
